### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by shaicoleman** [jcoleman/relation_to_struct#10]
At the moment the latest Rails seems to be unsupported
```
  spec.add_dependency "activerecord", ">= 5.0", "< 5.2"
  spec.add_dependency "activesupport", ">= 5.0", "< 5.2"
```

**Comment by jcoleman** [comment]
The apps I’m using this in are still on 5.1, so I haven’t gotten around to evaluating any changes 5.2 may have made that would cause problems.

If you’d like to open a PR with the max Rails version bumped, the tests will automatically run on the PR, and we can see if there’s any breakage.

**Comment by shaicoleman** [comment]
It gives the following errors when running the specs:
```
NameError: undefined local variable or method `bound_attributes' for #<ActiveRecord::Relation []>
# ~/.rvm/gems/ruby-2.5.3@cashanalytics/gems/activerecord-5.2.2/lib/active_record/relation/delegation.rb:125:in `method_missing'
```

It seems Rails 5.2 removed the bound_attributes method in this commit
https://github.com/rails/rails/commit/213796fb4936dce1da2f0c097a054e1af5c25c2c

**Comment by shaicoleman** [comment]
Thanks for merging and publishing a new version
